server:
  port: 5000
#
# JDBC properties
#
app:
  datasource:
    jdbc-url: jdbc:mysql://aa1i9u1ehuvzeo1.cpstvwcip2y8.eu-north-1.rds.amazonaws.com:3306/citizen_directory?allowPublicKeyRetrieval=true
    username: avgonaDB
    password: DBPassword

  # Spring Data JPA properties
spring:
  data:
    jpa:
      repository:
        packages: com.avgona.citizencrud.repository
      entity:
        packages-to-scan: com.avgona.citizencrud.entity
  profiles:
    active: @spring.profiles.active@

  #
  # SECURITY JDBC properties
  #

security:
  datasource:
    jdbc-url: jdbc:mysql://aa1i9u1ehuvzeo1.cpstvwcip2y8.eu-north-1.rds.amazonaws.com:3306/spring_security_demo_bcrypt?allowPublicKeyRetrieval=true
    username: avgonaDB
    password: DBPassword