server:
  port: 5000

# JDBC and Spring Data JPA properties
#
spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/citizen_repository?useSSL=false&serverTimezone=UTC
    username: root
    password: 9682
  data:
    repositories:
      packages: com.avgona.citizencrud.repository
    entities:
      packages-to-scan: com.avgona.citizencrud.entity
    mongodb:
      uri: mongodb://localhost:27017/avgona_db


# SECURITY JDBC properties
#
security:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/citizen_security?useSSL=false&serverTimezone=UTC
    username: root
    password: 9682